--- 
- name: grant tomcat ownership on tomcat folder 
  command: 
     cmd: sudo chown -R tomcat:tomcat /opt/tomcat/
- name: give excute permission on bin folder 
  command: 
     cmd: sudo chmod -R u+x /opt/tomcat/bin
